### ISSUE TITLE
Change labels of NS sensor on charts

### ISSUE THREAD

**Issue by balis** [ismop/eitwid#105]
Change labels of NS sensors on charts to more meaningful, such that allow identification of the sensors' locations. For example "neosentio.3_26_0_4 (Temperatura)". However, Daniel Kessler said that these IDs may change.

**Comment by dharezlak** [comment]
This is rather a pure DAP request...

**Comment by dharezlak** [comment]
Created: https://github.com/ismop/dap/issues/119
