### ISSUE TITLE
Stały kolor i pogrubienie linii dla wykresu poziomu wody

### ISSUE THREAD

**Issue by balis** [ismop/eitwid#113]
Zrobić tak, żeby poziom wody na wykresie był wyróżniony:
- miał zawsze ten sam kolor, np. niebieski. 
- linia była nieco pogrubiona

**Comment by mkasztelnik** [comment]
To sie odnosi do nowego widoku wysokosci wody, czy zawsze jak dodawany jest poziom wody to powinien byc grubszy i w jednolitym kolorze?
