### ISSUE TITLE
Register a new Experiment object to represent the real experiment starting on Aug 22

### ISSUE THREAD

**Issue by nowakowski** [ismop/eitwid#121]
Also register the following simulated wave height:
- Experiment commences on Aug 22, 9:30 am
- water level is to increase linearly over 48 hours, reaching 4.0m
- a 48-hour plateau (unchanged state) is scheduled
- finally, the reservoir will be emptied (again, linearly) over a period of 144 hours (6 days)

**Comment by nowakowski** [comment]
Never mind - already done, I see. ;)

**Comment by mkasztelnik** [comment]
Not yet. I need to calculate 1 hours steps - work in progress

**Comment by mkasztelnik** [comment]
Now it is done :dancers:
