### ISSUE TITLE
Unable to add simulated water level to experiment view

### ISSUE THREAD

**Issue by nowakowski** [ismop/eitwid#122]
Only the actual water level and power consumption are available. Perhaps it's by design (but why?)

**Comment by nowakowski** [comment]
![eitwid_experiment](https://cloud.githubusercontent.com/assets/4568385/17819157/e9927010-6646-11e6-8577-adb5d1de8c57.png)

**Comment by mkasztelnik** [comment]
Deployed into dev, waiting for @dharezlak for prod release
