### ISSUE TITLE
Profile with 4 id is unable to render on profile view

### ISSUE THREAD

**Issue by mkasztelnik** [ismop/eitwid#168]
Most probably dap data are corrupted. Can you take a look at this issue?

**Comment by dharezlak** [comment]
Is this the profile you mean:
![screenshot from 2016-11-18 10 53 20](https://cloud.githubusercontent.com/assets/1506876/20426007/7fb3ddfe-ad7d-11e6-89ef-913436cbbc5a.png)
![screenshot from 2016-11-18 10 53 27](https://cloud.githubusercontent.com/assets/1506876/20426008/7fb738c8-ad7d-11e6-805f-714738fb9fb6.png)

It rendered just fine on production.

**Comment by mkasztelnik** [comment]
Ok it also works on my browser, but sometime it requires 20 or more seconds to render this view. What is strange such lag is noticeable only on profile with internal id 4
