### ISSUE TITLE
Draw UI view concepts

### ISSUE THREAD

**Issue by mkasztelnik** [ismop/eitwid#3]
* [x] @dharezlak Monitoring view (dike view, real data view)
  * [x] @dharezlak Weather station view
  * [x] @mkasztelnik: Fiber sensor view
  * [x] @mkasztelnik: Analysis view
    * [x] @mkasztelnik: Plot analysis view
    * [x]  @bwilk: Cross-section view (przekrój poprzeczny) view
    * [x]  @bwilk: Longitudinal section (przekrój podłużny) view

**Comment by mkasztelnik** [comment]
Fiber sensor view

![fiber_sensor_view](https://cloud.githubusercontent.com/assets/1265430/9597418/bb281a62-5081-11e5-94fa-841f413bea04.jpg)

**Comment by balis** [comment]
My nie pokazujemy przekroju "podłużnego", tylko "poziomy". Terminy chyba są takie:
- vertical cross section view (widok przekroju poprzecznego)
- horizontal cross section view (widok przekroju poziomego)

**Comment by mkasztelnik** [comment]
Sensor plot view

![sensor_plot_view](https://cloud.githubusercontent.com/assets/1265430/9598538/d59fe7f2-508c-11e5-9e7f-2ba9d478a149.jpg)

**Comment by mkasztelnik** [comment]
Experiment analysis view

![experiment_analitics](https://cloud.githubusercontent.com/assets/1265430/9599934/e46c38c0-5097-11e5-902e-3fe6fb27b9fc.jpg)

**Comment by dharezlak** [comment]
Monitoring view

![ui-sketch](https://cloud.githubusercontent.com/assets/1506876/9599954/1ae6ba56-5098-11e5-971f-bf7150dfea00.png)

**Comment by dharezlak** [comment]
Dla Fiber sensor view trzeba jeszcze wziac pod uwage mozliwosc przelaczenia sie na widok z pojedynczym przebiegiem.

**Comment by bwilk** [comment]
Panel profilu - chciałbym to przedyskutować:
https://moqups.com/bwilk/na1owwuq/p:af0c578b8

**Comment by mkasztelnik** [comment]
@bwilk troche zduplikowales 2 widoki, ktore narysowalem (2 ostatnie moje komentarze). 
  * Ja zalozylem, ze eksperyment wybierany jest "poza" widokiem i jak widok juz jest otwarty nie da sie zmienic "eksperymentu", wtedy odpada problem ze zmiana eksperymentu. 
  * Nie rozumie po co jest "wykres pomocniczy", nawigacja po czasie eksperymentu i tak bedzie sie odbywac przez slider, ktory masz narysowany powyzej "wykresu pomocniczego". Jesli czlowiek chce zobaczyc jakis wykres to po prostu moze sobie dodac nowy element do widoku
  * Ja w widoku plota zalozylem, ze glowne okno jest jedynie readonly. Jesli czlowiek chce go zmodyfikowac to klika przycisk edit i tam moze dodawac/usowac serie. To jest do przedyskutowania jeszcze z @dharezlak, bo on zalozyl podobnie jak Ty, ze mozna edytowac wykres w glownym widoku
  * Metadane to b. fajna kontrolka tutaj, pytanie czy jesli bedzie zaznaczony przekruj to rowniez mamy jakies metadane na jej temat?

**Comment by mkasztelnik** [comment]
@bwilk mozliwe ze ja nie zrozumialem "wykresu pomocniczego", czy to jest wykres pokazujacy fale powodziowa symulowana w trakcie eksperymentu?

**Comment by dharezlak** [comment]
- wyrzucic listbox dla levee,
- pamietanie okna analityki (w bazie, sesji, cookie, itd.),
- mozliwosc przejscia z widoku monitoringu do analityki dla wybranych przebiegow,
- heatmapy w widoku monitoringu,
- wybor typu wykresu dla danej serii danych,
- zapytac Michala czy dla danych zewnetrznych beda symulowac wszystkie trzy profile (takich jak temp. zewn.)
- wizard dla profilu poziomego: predefiniowane zakresy wysokosci (na razie tylko budokop), wybor parametru, typ danych (symulowane czy rzeczywiste)
