### ISSUE TITLE
Chart wizard z-indexes broken and more meaningful names needed

### ISSUE THREAD

**Issue by dharezlak** [ismop/eitwid#34]
![screenshot from 2015-11-05 10 48 57](https://cloud.githubusercontent.com/assets/1506876/10965110/268e2df8-83ab-11e5-8bca-0730dc3fdab6.png)

Plain numbers do not tell anything about the choices the user has.

**Comment by mkasztelnik** [comment]
Quick hack to hide this bug is to limit number of shown elements to 5

**Comment by mkasztelnik** [comment]
Number of row is limited into 5 and this is the best option I found. List cannot be shown above modal, because when slider is used than list should disappear after section is scrolled down or up.
