### ISSUE TITLE
Horizontal intersection wizard chooses all scenarios

### ISSUE THREAD

**Issue by mkasztelnik** [ismop/eitwid#37]
Number of scenarios should be limited only to those which are assigned to selected experiment. Right now all scenarios are shown.

**Comment by dharezlak** [comment]
The query generated by the wizard is the following: /api/v1/scenarios?experiment_id=2, so it look like the selected experiment is taken into account. However, the scenario DAP entity does not have an experiment_id field but experiment_ids instead. Is this right? Should not there be a one-to-many relationship from experiment to scenario? If the model if fine how can we query for scenarios with a given experiment_id when there is an array of experiment ids in DAP?

**Comment by mkasztelnik** [comment]
@nowakowski can you answer this question?

**Comment by nowakowski** [comment]
To answer your first question: an experiment can process multiple scenarios and a single scenario can be processed by multiple experiments so the relationship is m:n.

**Comment by nowakowski** [comment]
Regarding queries, simply pass a one-element array (if interested in a specific experiment).

**Comment by dharezlak** [comment]
Something like the following: `/api/v1/scenarios?experiment_ids=[2]`? Currently, the result is an empty list of scenarios and I am quite sure there are scenarios with experiment id equal to `2`.

**Comment by dharezlak** [comment]
@nowakowski: Should I create a separate DAP issue for this?

**Comment by nowakowski** [comment]
@dharezlak Try `/api/v1/scenarios?experiment_ids=2`.

**Comment by dharezlak** [comment]
That did the trick. Thanks!
