### ISSUE TITLE
horizontal and vertical cross sections show nothing

### ISSUE THREAD

**Issue by mkasztelnik** [ismop/eitwid#38]
![screenshot from 2015-11-05 23 49 37](https://cloud.githubusercontent.com/assets/1265430/10984191/16906818-8418-11e5-9e97-1b0937234bed.png)

**Comment by mkasztelnik** [comment]
A loooooooot of "Uncaught TypeError: Expecting a function in instanceof check, but got undefined" is thrown in JS console for Horizontal crosssection view

**Comment by mkasztelnik** [comment]
A looooooot of "Uncaught TypeError: Cannot read property 'array' of undefined" is thrown in JS console for Vertical crosssection view

**Comment by dharezlak** [comment]
Another case of missing 3D renderer. Show a popup message explaining the errors.
