### ISSUE TITLE
Nothing is shown on profile view

### ISSUE THREAD

**Issue by mkasztelnik** [ismop/eitwid#39]
![screenshot from 2015-11-05 23 54 11](https://cloud.githubusercontent.com/assets/1265430/10984267/8e6b555a-8418-11e5-9794-ed4621c4091d.png)

**Comment by mkasztelnik** [comment]
Following exception is thrown: "Uncaught TypeError: Cannot read property 'i' of undefined"

**Comment by dharezlak** [comment]
This is caused by a missing 3D renderer. A user-friendly message should be shown to the user.

**Comment by Nuanda** [comment]
+1
