### ISSUE TITLE
Implement fibre widget

### ISSUE THREAD

**Issue by dharezlak** [ismop/eitwid#4]

**Comment by dharezlak** [comment]
Look at: https://github.com/ismop/eitwid/issues/3#issuecomment-136596869

**Comment by mkasztelnik** [comment]
Fibre view implemented and merged into development.

**Comment by mkasztelnik** [comment]
Final version:

![fibre_view](https://cloud.githubusercontent.com/assets/1265430/10045198/0d05d2da-6201-11e5-9afe-6be38fd6af51.png)
