### ISSUE TITLE
Show different icons for different types of devices/aggregations

### ISSUE THREAD

**Issue by dharezlak** [ismop/eitwid#43]

**Comment by mkasztelnik** [comment]
There are 4 types of icons: 
  - cold for neosentio device
  - cold for neosentio device aggregation
  - warm for budokop device
  - warm for budokop device aggregation

@dharezlak do you think it is enough or something more  sophisticated is needed?

**Comment by dharezlak** [comment]
I had in mind to use different shapes for different types of features. E.g. triangles for aggregations and circles for devices.

**Comment by mkasztelnik** [comment]
This is already in place. "..." inside circle for device aggregation and 3 circles inside circle :smile: for device. Additional different colours for different vendors. If this is enough than this issue can be closed.

**Comment by dharezlak** [comment]
Yes, but this is something that is practically invisible when looking at the map. Something more visible is needed but we can ignore it for now.
