### ISSUE TITLE
Use different color scheme for devices/profiles of different device providers

### ISSUE THREAD

**Issue by dharezlak** [ismop/eitwid#44]
Warm/Cold color schemes.

**Comment by mkasztelnik** [comment]
I can deal with it but please give me more details: should colour be specific for `Device#device_type` and `DeviceAggregation#device_aggregation_type` or for something else?

**Comment by dharezlak** [comment]
Devices and profiles have to be distinguished based on their project provider. There are two providers and for one of them blueish (cold) colouring should be used and for the other a reddish (warm) palette. The following DAP ticket should help when implemented: https://github.com/ismop/dap/issues/19.

**Comment by mkasztelnik** [comment]
I understand that https://github.com/ismop/dap/issues/19 will help with `Profiles`, what about `Devices`? Maybe information about provider should be added there as well?

**Comment by dharezlak** [comment]
Yes, it looks like Device#deviceType is not enough to tell which provider it belongs to (e.g. for fibre sensors there is no indication about the provider). We can either change Device#deviceType structure to always carry informtion about the provider or add a separate field with this king of information.

**Comment by mkasztelnik** [comment]
@nowakowski both solutions proposed by @dharezlak are ok from my point of view. Please choose one and let me know know.

**Comment by nowakowski** [comment]
@mkasztelnik I choose to add `Device.manufacturer` as a separate field. This will be returned in the REST.

**Comment by mkasztelnik** [comment]
Great :smile_cat: - I'm waiting for the implementation.

**Comment by nowakowski** [comment]
@mkasztelnik Done; however I decided to name the field `Device.vendor` instead. Deployed to dap-dev. Value has been set to `budokop` for all Devices currently visualized by the GUI (i.e. all Devices which have a valid assignment to an existing Section). Before I merge this into master and deploy to prod I will need you to confirm that this is what you wanted.

**Comment by mkasztelnik** [comment]
It looks ok. @dharezlak what about `DeviceAggregation` do we need vendor field there as well?

**Comment by dharezlak** [comment]
Yes, we do.

**Comment by nowakowski** [comment]
Come on guys, you're trashing the data model. What sense does it make to have a `vendor` field in `Device` if `DeviceAggregation` requires an identical field? Avoiding redundancy is a prime concern in database design. Also, I was under the impression that the decision was mine to make ( @mkasztelnik : "Please choose one and let me know."). Now it seems the decision was @dharezlak 's after all.

I will not push this to production until you've come to an agreement between yourselves on how to proceed. Adding `vendor` to both `DeviceAggregation` and `Device` is bad design.

**Comment by dharezlak** [comment]
Note, that we are not discussing the model itself but the REST structure. Internally it is up to you to do it right. Currently, the UI shows at some point devices, device aggregations and profiles. All these need to have information about the vendor to properly do the look-and-feel stuff without making extra requests.

Regarding device aggregations I would suggest (and this is my personal opinion) to retrieve the vendor info from the constituent devices and add the information in the controller.

**Comment by nowakowski** [comment]
@dharezlak But what if an aggregation contains devices from two (or more) different vendors?

**Comment by dharezlak** [comment]
Let's make it a list then, although this is very unlikely, but let's prepare for the worst case scenario.

**Comment by nowakowski** [comment]
List it is. Deployed to dap-dev. Please notify me whether this is satisfactory.

**Comment by dharezlak** [comment]
Looks good. Is the singular vendor approach for profiles going to be around or will it be re-factored in the near future?

**Comment by nowakowski** [comment]
I'll do the same with Profiles (replacing `vendor` with `vendors`).

**Comment by nowakowski** [comment]
Done. Please run a final check and notify me when this can be pushed to production.

**Comment by nowakowski** [comment]
Merged and deployed to dap-prod.
