### ISSUE TITLE
Export data presented in plots as CSV files

### ISSUE THREAD

**Issue by dharezlak** [ismop/eitwid#45]

**Comment by mkasztelnik** [comment]
The plot capability should be available only on plot view? Answer to this question will allow to define where export button should be located. If export capability should be available to all analyse views than export button will be added into panel header and `pl.ismop.web.client.widgets.common.panel.IPanelContent` will be extended with `export` method

**Comment by dharezlak** [comment]
I think we should only have the export option in plots. Ideally as another export option in the dropdown menu next to png, pdf, etc. items.

**Comment by mkasztelnik** [comment]
Done in #82
