### ISSUE TITLE
Show if fiber is heated by appropriate plot background

### ISSUE THREAD

**Issue by dharezlak** [ismop/eitwid#47]

**Comment by mkasztelnik** [comment]
@nowakowski please let me in which sensor information about fiber heating turned on/off is stored.

**Comment by nowakowski** [comment]
@mkasztelnik No such information is reported to DAP by MOM.

**Comment by mkasztelnik** [comment]
Can you kontakt Marek K. and ask about it? He was mentioning month ago that this information will be reported by MOM.

**Comment by nowakowski** [comment]
@mkasztelnik Already have.

**Comment by mkasztelnik** [comment]
@nowakowski any response from Marek?

**Comment by nowakowski** [comment]
Yep, we have obtained the following reply:

"dostajecie tą informacje: ASP.HEATING_UPPER i ASP.HEATING_BOTTOM. Ponieważ jest to 'sensor ręczny' podczas ostatniej zabawy nikt nie kliknął że coś robią - dlatego nie ma tej informacji."

So, look for Parameters with these custom IDs.

**Comment by mkasztelnik** [comment]
Can you create device for it? Something I can use to correlate these values with concrete fibre.

**Comment by nowakowski** [comment]
Aye, done. Also created a `DeviceAggregation` object (label: `FO Heating`). However, no "measurements" are actually available for these parameters and my message to MK (sent several days ago) asking him to create some measurements has gone unanswered.

**Comment by mkasztelnik** [comment]
@nowakowski would it be possible to reorganize it a little bit. It would be much simpler for me to have something like:

  * `DeviceAggregation` with `device_aggregation_type` set to `fibre`
  * `DeviceAggregation` has many devices. Most of them will be with type `fiber_optic_node` but one can be with type `fiber_heating`
  * `Device` with `fiber_heating` type has one parameter (`ASP.HEATING_UPPER` or `ASP.HEATING_BOTTOM`)

What do you think? If such structure will be implemented then it will be much more simpler for me to fetch  information about fiber heating devices (because I'm already asking about all devices and parameters belonging to `DeviceAggregations` with type set to `fiber`).

**Comment by mkasztelnik** [comment]
@nowakowski any update about this issue?

**Comment by nowakowski** [comment]
@mkasztelnik `Device.device_type` is not a simple enum - it is a key upon which Device polymorphism is based, and each supported value corresponds to a separate model table which contains type-specific metadata. As such, the list of supported device types is hardcoded in the model structure. It can, of course, be extended, but this requires a PR and a new set of DB tables.

Seems like a big change just to simplify a single GET. Are you sure you want it done your way?

**Comment by mkasztelnik** [comment]
Otherwise I need to hardcode concrete device Id in UI which I would like to avoid (right now whole UI is created in generic way not specific to ISMO levee). Maybe changing table inheritance into simple json with metadata is a solution? Then introducing new device type should be very simple.

**Comment by nowakowski** [comment]
Following consultation - two `DeviceAggregation` objects (one per FO) have been extended with an additional `Device` of type `budokop-sensor` which aggregate heating sensor data. This change was performed on dap-dev only to avoid breaking the production UI. Please notify when you want this change carried over to dap-prod.

**Comment by mkasztelnik** [comment]
Thx. In the following days I will be implementing this issue, when it will be ready I will let you know.
