### ISSUE TITLE
Implement weather station widget

### ISSUE THREAD

**Issue by dharezlak** [ismop/eitwid#5]

**Comment by dharezlak** [comment]
Take a look at: https://github.com/ismop/eitwid/issues/3#issuecomment-136640158

**Comment by dharezlak** [comment]
Try to extract a common chart widget to be reused elsewhere in the app.

**Comment by dharezlak** [comment]
A common chart widget is already extracted and may be reused. Have a look at `pl.ismop.web.client.widgets.common.chart.ChartPresenter`.

**Comment by bwilk** [comment]
Ok. Thanks. I will reuse it for convenience of further changes

**Comment by mkasztelnik** [comment]
@bwilk do you have first version of the weather station view already?
