### ISSUE TITLE
Create a third panel with live levee preview

### ISSUE THREAD

**Issue by dharezlak** [ismop/eitwid#53]
- plots in this should be updated automatically,
- the layout should be customizable and persistent (user-defined with a couple of predefined views)

**Comment by mkasztelnik** [comment]
I propose to implement it first on experiment view - when experiment is in progress all views are updated using defined interval. 

The plus of such solution is that we already have this view and autorefresh can be easily added there. When this is ready and tested it should be easy to port it into live monitoring tab.

**Comment by dharezlak** [comment]
Let's start with a whiteboard and discuss how the third view should look like. Maybe we will finish with something completely different than current views. Also, current analysis (experiment) view should be used to analyse historical data and as such a live-preview feature will not be used at all. At least that is how I see it.

**Comment by dharezlak** [comment]
Below is my proposal for the third view ready to be discussed. I propose to disregard the request to build a full-blown wizard for this view and just prepare an arbitrary layout using the widgets we already have (with modifications).
![ui-sketch-view-5](https://cloud.githubusercontent.com/assets/1506876/11950512/43eec620-a889-11e5-896f-c7d6b6b06545.png)

**Comment by nowakowski** [comment]
@dharezlak Color-coding profiles may be useful when visualizing soil type. Instead of marking the selected profile with a different color perhaps you could highlight its outline?

**Comment by dharezlak** [comment]
Available on the development environment.
