### ISSUE TITLE
All experiment data export should be possible

### ISSUE THREAD

**Issue by dharezlak** [ismop/eitwid#58]

**Comment by mkasztelnik** [comment]
@nowakowski, @bwilk I believe export should be done on the DAP side, most probably using background task. My proposition is to have something like this:

1. User requests experiment data export (we can provide user email in this email)
2. When the export was not created yet 202 response code ([according to this advice](http://stackoverflow.com/questions/9794696/best-http-status-code-in-rest-api-for-not-ready-yet-try-again-later)) is returned and in the same time export delayed job is triggered with user email.
3. After export is ready user receives email with information that data is ready
4. Now every request to the URL defined in point 1 returns zip with all experiment data

Challenges:

1. Active experiments should not be cached or it should be not possible to export experiment data before experiment end.

What do you think about this scenario? Can it be implemented in such a way?

**Comment by nowakowski** [comment]
@mkasztelnik Possibly, with a bit of work (what happens when multiple requests arrive? How do we protect DAP against being DOSed by this fairly I/O-heavy operation? How to cancel pending requests?)

**Comment by nowakowski** [comment]
@mkasztelnik Please specify what output format is required (item 4 - "zip with all experimental data" is quite vague).

**Comment by mkasztelnik** [comment]
@nowakowski format should be agreed with prof Lesniak team.

**Comment by nowakowski** [comment]
@mkasztelnik Then we will eagerly await input from Prof Lesniak's team. :)

**Comment by mkasztelnik** [comment]
Someone from DAP team should contact Prof Lesniak's team and start conversation...

**Comment by nowakowski** [comment]
@mkasztelnik Ehm, aren't they the ones making the request? It would seem to me someone from Prof. Leśniak's team should contact the DAP team and start conversation. ;)
