### ISSUE TITLE
Loading time series is not very efficient

### ISSUE THREAD

**Issue by Nuanda** [ismop/eitwid#63]
I know this may have a thousand causes server-side, but from the UX point of view, this is what is instantly judged by the users. In my opinion 5.5 sec delay to load 300 KB of data is rather too much.

Possible optimization strategies:
 - turn on gzip server-side, if not already turned on (much smaller transfer times, currently 0.5 sec; already discussed with @mkasztelnik)
 - replace JSON generator to faster one (already hinted @nowakowski on a possible in-place replacement for up to 2x speedup)
 - use the more efficient InfluxDB store to fetch data, instead of slower PostgreSQL
 - depending on the frequency of readings, some caching strategies could be possible.

**Comment by mkasztelnik** [comment]
gzip was turned on in `dap` and `dap-dev`

**Comment by Nuanda** [comment]
Did it help?

**Comment by mkasztelnik** [comment]
Not really. DB queries are still the biggest problem, but @nowakowski is working on this issue right now. According to Piotr influxDB should be ready in the middle of January - theoretically it should help.

**Comment by nowakowski** [comment]
Yeah, I did activate gzip, but come on, did anyone expect it to help? :) Typical message payload is several KB; how much transmission time will be saved by gzipping it? Note that this has to be weighted against the additional cost of message compression/decompression.

The bottleneck lies elsewhere. We currently have over 25,000,000 measurements yet the application requires real-time query capabilities. This has to be addressed on the level of the database; anything else is just window dressing.

**Comment by Nuanda** [comment]
Of course it could. I noticed >300 KB payloads, so much larger than "several". Large multiplication of same words suggest high compression ratio. Gzipping time is negligible, transfer time, esp. with slower network (think: GSM) is not.

**Comment by nowakowski** [comment]
Well, it probably didn't make it any worse, at least. :)

**Comment by Nuanda** [comment]
It brought 300 KB responses down to 12 KB responses, if I'm not mistaken. @mkasztelnik @nowakowski  can you confirm that? But the UI is now much faster, probably due to other reasons as well - so it's difficult to compare.

**Comment by mkasztelnik** [comment]
@Nuanda you are right gzip is doing very good job :smile:

**Comment by nowakowski** [comment]
Meanwhile, however, the FO view is triggering 504 errors. @bwilk has been tweaking the queries recently - this may have caused a performance hit.

**Comment by mkasztelnik** [comment]
@Nuanda queries are improved by @nowakowski (right now only on ui-dev) - take a look if it is good enough right now.

**Comment by mkasztelnik** [comment]
UI is quite fast right now. I believe that we can close it. @Nuanda please reopen if you think that we can do better.
