### ISSUE TITLE
Remove time constraints on data requests

### ISSUE THREAD

**Issue by dharezlak** [ismop/eitwid#68]

**Comment by dharezlak** [comment]
Due to heavy load on the database data retrieval was limited to only one month of history data. Also, last measurement retrieval was limited to two hour time window. Now, that the DB's performance was improved these limitations must go.

**Comment by dharezlak** [comment]
The last piece of this issue is the fibre view which still uses a "time windowed version" of retrieval of last measurements.

**Comment by mkasztelnik** [comment]
We agreed today that this time window should be available for fibre query -> closing.

**Comment by dharezlak** [comment]
After checking we need to revert weather station view to use the time window approach. Currently it is loading for too long.

**Comment by dharezlak** [comment]
OK, currently the time window used by the fibre view is 24 hours long and it takes around 3 seconds to get the latest readings. Extending the period to two weeks as we agreed makes the query take 40 seconds. I am going to apply the 24 hours time window querying to the weather station as well.
