### ISSUE TITLE
Add a hint text to the start date window in the fiber view

### ISSUE THREAD

**Issue by dharezlak** [ismop/eitwid#70]
Currently, it is a guessing game to set the start date in the fiber view. Users should be informed about the oldest available measurements. A title attribute on the start date text box should suffice.

**Comment by mkasztelnik** [comment]
@nowakowski please let me know what is the best way to get first existing result for selected sensors ever. Is it be possible in quite short sql query time?

**Comment by nowakowski** [comment]
If you need this query processed really fast then the best I can think of is to denormalize the Timeline model by adding two additional fields (`initial_measurement_date` and `initial_measurement_value`) which you would be able to read directly.

**Comment by mkasztelnik** [comment]
I think that up to 1s is acceptable.

**Comment by nowakowski** [comment]
Please file a DAP ticket and I'll take care of it.
