### ISSUE TITLE
Use the water level device wherever applicable in the UI

### ISSUE THREAD

**Issue by dharezlak** [ismop/eitwid#84]
Places that come to mind: analysis panel water level widget, additional readings list in the readings pop-up.

**Comment by mkasztelnik** [comment]
@nowakowski please let me know what is the water sensor name and type

**Comment by nowakowski** [comment]
@mkasztelnik @dharezlak I have manually created the required objects on dap-prod:

  - 1 DeviceAggregation with `custom_id == 'pump_monitoring'`
  - 1 Device of type `pump` with `custom_id == 'pump_monitoring'` belonging to the above

The new device aggregates all five pump monitoring Parameter objects reported by MOM; specifically:

  - Four water level indicators (with custom_ids `'pumpMonitoring.ASP_Level1_PV'`, `'pumpMonitoring.ASP_Level_PV'`, `'pumpMonitoring.ASP_Level_SP'` and `'pumpMonitoring.ASP_Level2_PV'` respectively)
  - One power level monitoring indicator (with `custom_id == 'pumpMonitoring.powerUsage'`)

Each of these contains a single timeline with real measurements as per standard procedure.

**Comment by mkasztelnik** [comment]
Please let me know which parameter is water high

**Comment by nowakowski** [comment]
What's "water high"?

**Comment by mkasztelnik** [comment]
The amount of water we currently have in levee, in e.g. cm.

**Comment by nowakowski** [comment]
"They're all your hats, Mr. Angiers." ;) Seriously though, the four ASP parameters mentioned above all return water level indications, presumably at various points along the embankment. I am trying to contact MM to find out which points these are -- he's not answering his phone but I've sent him an e-mail.

Looking at the readings suggests that `pumpMonitoring.ASP_Level_SP` might be the "absolute" water level indicator since it peaked at 1.0 yesterday and from what @balis told me the experiment involved filling the reservoir up to a height of 1 m.

Oh, and the unit is [m] (i.e. 0.98 means 98 cm).

**Comment by mkasztelnik** [comment]
@nowakowski can you populate pump device and measurement into dap-dev? I need it to test UI changes.

**Comment by nowakowski** [comment]
@mkasztelnik This is no longer easy because the DB needs to be repartitioned. I can schedule it, but it will take several hours and all existing dap-dev data will be lost. Should I proceed?

**Comment by mkasztelnik** [comment]
Is it possible to create missing devices and migrate only missing data for these concrete devices? 

@bwilk as you can see data duplication to both prod and dev environments are crucial right now. Can you let us know when flume will be writing data to both environments?

**Comment by nowakowski** [comment]
@mkasztelnik I don't see an easy way to do this. I will start the migration process now - like I said, it'll take several hours.

**Comment by nowakowski** [comment]
@mkasztelnik @dharezlak Done - try it now.

**Comment by mkasztelnik** [comment]
@nowakowski :+1:
@bwilk when data replication into prod and dev will be working?

**Comment by bwilk** [comment]
@mkasztelnik I suppose it may be possible this friday

**Comment by mkasztelnik** [comment]
good :smile:
