### ISSUE TITLE
Strange string displayed in FO timescale textbox

### ISSUE THREAD

**Issue by nowakowski** [ismop/eitwid#89]
See attached screenshot. Captured on dap-dev with Chrome 47 under Linux
![portal6](https://cloud.githubusercontent.com/assets/4568385/13839625/ba55b626-ec1c-11e5-99f1-7a587d7d4ed7.png)

**Comment by mkasztelnik** [comment]
This problem occurs after date is changed

**Comment by nowakowski** [comment]
This seems to happen when there are no measurements at all which satisfy the input criteria (i.e. fall within the default date range).
