### ISSUE TITLE
No data displayed in FO view despite correct response from DAP

### ISSUE THREAD

**Issue by nowakowski** [ismop/eitwid#91]
See attached screenshot. The FO view gets stuck in "loading data" mode even though a correct set of measurements is received from DAP. Observed on prod following deployment of latest DAP version.
![ui_bug_6](https://cloud.githubusercontent.com/assets/4568385/14558185/45169a0a-0301-11e6-9fea-9bc216ba11f1.png)

**Comment by dharezlak** [comment]
Production UI has just been released with the latest last-second fix provided by @mkasztelnik. All should work well from now on.
