### ISSUE TITLE
Exact date specification is needed when exporting data

### ISSUE THREAD

**Issue by dharezlak** [ismop/eitwid#94]
Implementation proposal:
Add another export option `Download as CSV document...` which will show an additional pop-up with date pickers for start and end dates. Default values of the date pickers will be the ones coming from the chart. The pickers should allow to pick dates with the granularity of days. Assume that the start date picker starts at midnight of a given day and the end date picker ends at midnight of a given day (e.g. exporting data which is one day long would need to pick the same day in both date pickers).

**Comment by dharezlak** [comment]
Maybe the same behaviour should be implemented for the experiment data export flow...

**Comment by mkasztelnik** [comment]
This is a requirement from Geologia or just improvement proposed by you?

**Comment by mkasztelnik** [comment]
To simplify the process modal with time interval selection is always shown with from/to dates fetched from chart `xExtremes`.
